### ISSUE TITLE
inference error with wrong kwargs max_batch_size in hdf5 format

### ISSUE THREAD

**Issue by zmingshi** [bytedance/lightseq#123]
hi, I install the latest version:
`lightseq == 2.0.3`

```shell
python hf_gpt2_export.py
python ls_gpt.py
```
it throws the error like this.
```shell
$python ls_gpt.py
initializing gpt tokenizer...
lightseq tokenizer pad token id: 50257
huggingface tokenizer pad token id: 50256
creating lightseq model...
Traceback (most recent call last):
  File "ls_gpt.py", line 119, in <module>
    main()
  File "ls_gpt.py", line 79, in main
    ls_model = lsi.Gpt("lightseq_gpt2_base.hdf5", max_batch_size=16)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. lightseq.inference.Gpt(weight_path: str, max_batch_size: int, max_step: int)

Invoked with: 'lightseq_gpt2_base.hdf5'; kwargs: max_batch_size=16
```
the latest tag v2.0.2 still uses the protobuf format, so the HDF5 format is not works now ?

**Comment by Taka152** [comment]
You can try 2.1.0, only this version support hdf5

**Comment by zmingshi** [comment]
> You can try 2.1.0, only this version support hdf5

thanks, it works now!
