### ISSUE TITLE
overflow for larger models

### ISSUE THREAD

**Issue by szha** [bytedance/lightseq#198]
Hi,

The following part of calculation for weight size can easily overflow for models larger than 16GB

https://github.com/bytedance/lightseq/blob/master/lightseq/inference/proto/gpt_weight.cc#L338-L343

The calculation in parentheses happens in int as all fields are of int type, and the result is then cast to `size_t` when saving the result.

**Comment by szha** [comment]
So far I have a patch that fixes the overflow problem in loading weights, though the generation still doesn't work yet. Some of the fixes that helped me get through the weight loading can be found at [here](https://github.com/bytedance/lightseq/compare/master...szha:fix_overflow?expand=1)

<details><summar>Error log</summary>

```
$ python3.8 ls_gpt2.py --file gpt2-3.3b.hdf5
initializing gpt tokenizer...
lightseq tokenizer pad token id: 50257
huggingface tokenizer pad token id: 50256
creating lightseq model...
Parsing hdf5: gpt2-3.3b.hdf5
loading 785 MB of embedding weight.
finish initializing emb_wei from host to device
loading 12288 MB of encoder weight.
value: 3222077440
layers: 16
hidden: 4096
inner: 16384
size: 4
finish initializing enc_wei from host to device
Finish loading all weight from host to device
Allocated 7MB GPU buffer for GPT2
creating huggingface model...
====================START warmup====================
=========lightseq=========
lightseq generating...
batch_size-1 batch_seq_len-5
Sample with topk
padding_id: 64753760
vocab_size: 50257
batch_token_ids: 3666, 1438, 318, 402, 11571,
embedding: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
input with bias: 0, 0, 0, 0, 0,
first ln output: 0, 0, 0, 0, 0,
hidden_size: 4096
_batch_token_num: 5
_dim_per_head: 128
_head_num: 32
qkv_weight_mat: 0.01828, 0.0180206, 0.04953, -0.0116043, 0.0281525,
_p_d_qkv_projected: 0, 0, 0, 0, 0,
_p_d_q: 0, 0, 0, 0, 0,
_p_d_k: 0, 0, 0, 0, 0,
_p_d_v: 0, 0, 0, 0, 0,
q*k: 0, 0, 0, 0, 0,
mask weights: 0, 0, 0, 0, 0,
value after attention: 0, 0, 0, 0, 0,
reshaped value after attention: 0, 0, 0, 0, 0,
attention input with output bias: 0, 0, 0, 0, 0,
attn out kernel: 0.0206604, 0.0281067, -0.0025177, 0.00169277, 0.00329781,
attention output: 0, 0, 0, 0, 0,
Traceback (most recent call last):
  File "ls_gpt2.py", line 117, in <module>
    main()
  File "ls_gpt2.py", line 93, in main
    warmup(ls_tokenizer, hf_tokenizer, ls_model, hf_model, sentences)
  File "ls_gpt2.py", line 57, in warmup
    ls_generate(ls_model, ls_tokenizer, ls_inputs)
  File "ls_gpt2.py", line 34, in ls_generate
    ls_res_ids, ls_time = ls_gpt2(model, inputs)
  File "ls_gpt2.py", line 13, in ls_gpt2
    generated_ids = model.sample(inputs)
RuntimeError: [CUDA][ERROR] /tmp/build-via-sdist-yn262721/lightseq-2.1.3/lightseq/inference/model/gpt_encoder.cc.cu(705): CUBLAS_STATUS_EXECUTION_FAILED

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)
```

</details>

**Comment by Taka152** [comment]
Thanks for your PR. We will check this overflow for other models.
For your error log, it may be caused by incorrect weight exportation or
incorrect input. Since embedding output zero is unreasonable.

**Comment by szha** [comment]
@Taka152 the weight export script is direct adaptation from your example scripts, with the only difference in model hyperparameter settings in HF GPT-2 model. The zeros are just from an untrained initialized model.
