### ISSUE TITLE
Multi-calorie running model problem

### ISSUE THREAD

**Issue by xiao12mm** [bytedance/lightseq#444]
```
[INFO|trainer.py:1634] 2022-12-28 17:17:11,481 >> ***** Running training *****
[INFO|trainer.py:1635] 2022-12-28 17:17:11,481 >>   Num examples = 13000
[INFO|trainer.py:1636] 2022-12-28 17:17:11,481 >>   Num Epochs = 10
[INFO|trainer.py:1637] 2022-12-28 17:17:11,481 >>   Instantaneous batch size per device = 4
[INFO|trainer.py:1638] 2022-12-28 17:17:11,481 >>   Total train batch size (w. parallel, distributed & accumulation) = 8
[INFO|trainer.py:1639] 2022-12-28 17:17:11,481 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1640] 2022-12-28 17:17:11,481 >>   Total optimization steps = 16250
[INFO|trainer.py:1641] 2022-12-28 17:17:11,481 >>   Number of trainable parameters = 102269331
[INFO|trainer.py:1663] 2022-12-28 17:17:11,481 >>   Continuing training from checkpoint, will skip to saved global_step
[INFO|trainer.py:1664] 2022-12-28 17:17:11,481 >>   Continuing training from epoch 0
[INFO|trainer.py:1665] 2022-12-28 17:17:11,481 >>   Continuing training from global step 1000
[INFO|trainer.py:1667] 2022-12-28 17:17:11,481 >>   Will skip the first 0 epochs then the first 1000 batches in the first epoch. If this takes a lot of time, you can add the `--ignore_data_skip` flag to your launch command, but you will resume the training on data already seen by your model.
Skipping the first batches: 100%|█████████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 450.91it/s]
TransformerEncoderLayer #0 bind weights and grads.                                                               | 0/16250 [00:00<?, ?it/s]
TransformerEncoderLayer #0 bind weights and grads.
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #1 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #2 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #3 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #4 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #5 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #6 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #7 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #8 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #9 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #10 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
TransformerEncoderLayer #11 bind weights and grads.
!!!! kernel execution error. (m: 2304, n: 512, k: 768, error: 13)
!!!! kernel execution error. (batch: 48, m: 128, n: 128, k: 64, error: 13)
!!!! kernel execution error. (batch: 48, m: 64, n: 128, k: 128, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 3072, n: 512, k: 768, error: 13)
!!!! kernel execution error. (m: 768, n: 512, k: 3072, error: 13)
Traceback (most recent call last):
  File "/data/hu/code/lightseq/examples/training/huggingface/bert/task_glue/run_glue_mutli.py", line 716, in <module>
    main()
  File "/data/hu/code/lightseq/examples/training/huggingface/bert/task_glue/run_glue_mutli.py", line 621, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 1527, in train
    return inner_training_loop(
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 1775, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 2523, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 2555, in compute_loss
    outputs = model(**inputs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 1566, in forward
    outputs = self.bert(
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 1034, in forward
    pooled_output = self.pooler(sequence_output) if self.pooler is not None else None
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 662, in forward
    pooled_output = self.dense(first_token_tensor)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

  0%|                                                                                                            | 0/16250 [00:04<?, ?it/s]
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA][ERROR] /data/soft/anaconda3/envs/bert/lib/python3.9/site-packages/lightseq/csrc/kernels/cuda_util.cu(190): an illegal memory access was encountered

```
Key code:
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

I wanted to use multi-card training, I set (os.environ) and I found the key code

```
TrainingArguments(

_n_gpu=2,
```

Report mistakes during training. Where else should I set it?

**Comment by hexisyztem** [comment]
https://github.com/bytedance/lightseq/blob/master/examples/training/huggingface/bert/task_glue/run_glue.sh#L21
You can try this configuration.

**Comment by xiao12mm** [comment]
I found the answer:
[](https://pytorch.org/docs/stable/distributed.html#launch-utility)

parameter

`--nproc_per_node=1`

Play a role
