### ISSUE TITLE
Gpt exceeds maximum protobuf size of 2GB: 3096122166

### ISSUE THREAD

**Issue by zmingshi** [bytedance/lightseq#63]
when I use lightseq(2.0) export gpt2-large, it raises an error
`ValueError: Message Gpt exceeds maximum protobuf size of 2GB: 3096122166`

hf_gpt2_export.py is as follows
```python

if __name__ == "__main__":
    output_lightseq_model_name = "lightseq_gpt2_large.pb"
    input_huggingface_gpt_model = "gpt2-large"
    head_number = 36
    # generation_method should be "topk" or "topp"
    generation_method = "topk"
    topk = 1
    topp = 0.75
    # default eos_id from https://huggingface.co/transformers/model_doc/gpt2.html#gpt2lmheadmodel
    eos_id = 50256
    pad_id = 50257
    extract_gpt_weights(
        output_lightseq_model_name,
        input_huggingface_gpt_model,
        head_num=head_number,  # layer number
        generation_method=generation_method,
        topk=topk,
        topp=topp,
        eos_id=eos_id,
        pad_id=pad_id,
    )
```

```shell

['transformer.h.34.mlp.c_proj.bias'] -> ffn_second_bias, shape: (1280,), convert finished.
['transformer.h.35.ln_1.weight'] -> multihead_norm_scale, shape: (1280,), convert finished.
['transformer.h.35.ln_1.bias'] -> multihead_norm_bias, shape: (1280,), convert finished.
['transformer.h.35.attn.c_attn.weight'] -> multihead_project_kernel_qkv, shape: (1280, 3840), convert finished.
['transformer.h.35.attn.c_attn.bias'] -> multihead_project_bias_qkv, shape: (3840,), convert finished.
['transformer.h.35.attn.c_proj.weight'] -> multihead_project_kernel_output, shape: (1280, 1280), convert finished.
['transformer.h.35.attn.c_proj.bias'] -> multihead_project_bias_output, shape: (1280,), convert finished.
['transformer.h.35.ln_2.weight'] -> ffn_norm_scale, shape: (1280,), convert finished.
['transformer.h.35.ln_2.bias'] -> ffn_norm_bias, shape: (1280,), convert finished.
['transformer.h.35.mlp.c_fc.weight'] -> ffn_first_kernel, shape: (1280, 5120), convert finished.
['transformer.h.35.mlp.c_fc.bias'] -> ffn_first_bias, shape: (5120,), convert finished.
['transformer.h.35.mlp.c_proj.weight'] -> ffn_second_kernel, shape: (5120, 1280), convert finished.
['transformer.h.35.mlp.c_proj.bias'] -> ffn_second_bias, shape: (1280,), convert finished.
['transformer.ln_f.weight'] -> norm_scale, shape: (1280,), convert finished.
['transformer.ln_f.bias'] -> norm_bias, shape: (1280,), convert finished.
['transformer.wte.weight'] -> token_embedding, shape: (50257, 1280), convert finished.
['transformer.wpe.weight'] -> position_embedding, shape: (1024, 1280), convert finished.
Wrting to lightseq_gpt2_large.pb
Traceback (most recent call last):
  File "hf_gpt2_export.py", line 127, in <module>
    pad_id=pad_id,
  File "hf_gpt2_export.py", line 100, in extract_gpt_weights
    fout.write(gpt.SerializeToString())
ValueError: Message Gpt exceeds maximum protobuf size of 2GB: 3096122166
```

**Comment by Taka152** [comment]
Thanks for your feedback, we don't support a too big model now, because of protobuf max size limitation. We will consider solving this in the future.

**Comment by zmingshi** [comment]
> Thanks for your feedback, we don't support a too big model now, because of protobuf max size limitation. We will consider solving this in the future.

Large generation models like gpt2-large, gpt3 have good perfermance in text generation,  speedup is important to them, 
look forward to it

**Comment by Taka152** [comment]
> > Thanks for your feedback, we don't support a too big model now, because of protobuf max size limitation. We will consider solving this in the future.
> 
> Large generation models like gpt2-large, gpt3 have good perfermance in text generation, speedup is important to them,
> look forward to it

Thanks, we've noticed this limitation, and consider fix it next month.

**Comment by zmingshi** [comment]
@Taka152 
It seems that large models still have some problems. I pull the lasted codes and update lightseq==2.0.3

```shell
pip install -U lightseq
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, http://xpypi.alibaba-inc.com/pypi/
WARNING: Skipping page http://xpypi.alibaba-inc.com/pypi/lightseq/ because the GET request got Content-Type: application/json; charset=utf-8.The only supported Content-Type is text/html
Collecting lightseq
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7b/ec/f33fb0d218cc7479ec35e118f063707c27c5ba7621748c9adc0a90d4c002/lightseq-2.0.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.6 MB)
Requirement already satisfied: ninja in /online/mingcheng.szm/local/miniconda3/lib/python3.7/site-packages (from lightseq) (1.10.0.post2)
Installing collected packages: lightseq
Successfully installed lightseq-2.0.3
```

```shell
--- a/examples/inference/python/hf_gpt2_export.py
+++ b/examples/inference/python/hf_gpt2_export.py
@@ -125,9 +125,9 @@ def extract_gpt_weights(

 if __name__ == "__main__":
-    output_lightseq_model_name = "lightseq_gpt2_base"  # or "lightseq_gpt2_large"
-    input_huggingface_gpt_model = "gpt2"  # or "gpt2-large"
-    head_number = 12  # 20 for "gpt2-large"
+    output_lightseq_model_name = "lightseq_gpt2_medium"  # or "lightseq_gpt2_large"
+    input_huggingface_gpt_model = "gpt2-medium"  # or "gpt2-large"
+    head_number = 16  # 20 for "gpt2-large"
     # generation_method should be "topk" or "topp"
     generation_method = "topk"
     topk = 1

diff --git a/examples/inference/python/ls_gpt.py b/examples/inference/python/ls_gpt.py
index 04b379c..b569f6f 100644
--- a/examples/inference/python/ls_gpt.py
+++ b/examples/inference/python/ls_gpt.py
@@ -65,21 +65,21 @@ def main():

     print("initializing gpt tokenizer...")

-    ls_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
+    ls_tokenizer = GPT2Tokenizer.from_pretrained("gpt2-medium")
     # lightseq use len(tokenizer) as pad_token in default
     ls_tokenizer.add_special_tokens({"pad_token": "[PAD]"})
     print(f"lightseq tokenizer pad token id: {ls_tokenizer.pad_token_id}")

-    hf_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
+    hf_tokenizer = GPT2Tokenizer.from_pretrained("gpt2-medium")
     # use EOS as PAD for huggingface to avoid warning according to https://huggingface.co/blog/how-to-generate while avoid reshaping the model embedding
     hf_tokenizer.pad_token = hf_tokenizer.eos_token
     print(f"huggingface tokenizer pad token id: {hf_tokenizer.pad_token_id}")

     print("creating lightseq model...")
-    ls_model = lsi.Gpt("lightseq_gpt2_base.hdf5", max_batch_size=16, max_step=50)
+    ls_model = lsi.Gpt("lightseq_gpt2_medium.hdf5", max_batch_size=16, max_step=50)

     print("creating huggingface model...")
-    hf_model = GPT2LMHeadModel.from_pretrained("gpt2")
+    hf_model = GPT2LMHeadModel.from_pretrained("gpt2-medium")
     hf_model.to("cuda:0")
```

I test gpt2-medium and gpt2-large, it produces the same error as follows

```shell
$CUDA_VISIBLE_DEVICES=7 python ls_gpt.py
initializing gpt tokenizer...
lightseq tokenizer pad token id: 50257
huggingface tokenizer pad token id: 50256
creating lightseq model...
Traceback (most recent call last):
  File "ls_gpt.py", line 119, in <module>
    main()
  File "ls_gpt.py", line 79, in main
    ls_model = lsi.Gpt("lightseq_gpt2_medium.hdf5", max_batch_size=16, max_step=50)
RuntimeError: Parse weights from [lightseq_gpt2_medium.hdf5] failed.
```

**Comment by Taka152** [comment]
@zmingshi latest fix of the big model hasn't been updated to PyPI. You can build from the source or wait for a new pypi version.

**Comment by zmingshi** [comment]
> @zmingshi latest fix of the big model hasn't been updated to PyPI. You can build from the source or wait for a new 2.0.4 version. I'll try to update today.

 good job! wating for you~

**Comment by Taka152** [comment]
some tests failed, I'll try to release next week

**Comment by zmingshi** [comment]
> some tests failed, I'll try to release next week

@Taka152 
hi,  I install the latest version:
lightseq == 2.0.3

```shell
python hf_gpt2_export.py
python ls_gpt.py
```
it throws the error like this.

```shell
$python ls_gpt.py
initializing gpt tokenizer...
lightseq tokenizer pad token id: 50257
huggingface tokenizer pad token id: 50256
creating lightseq model...
Traceback (most recent call last):
  File "ls_gpt.py", line 119, in <module>
    main()
  File "ls_gpt.py", line 79, in main
    ls_model = lsi.Gpt("lightseq_gpt2_base.hdf5", max_batch_size=16)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. lightseq.inference.Gpt(weight_path: str, max_batch_size: int, max_step: int)

Invoked with: 'lightseq_gpt2_base.hdf5'; kwargs: max_batch_size=16
```

the latest tag v2.0.2 still uses the protobuf format, so the HDF5 format is not works now ?
