### ISSUE TITLE
UnboundLocalError: local variable 'logging_output' referenced before assignment

### ISSUE THREAD

**Issue by TIMAX-159** [bytedance/lightseq#94]
I tried to run the example in lightseq/examples/training/fairseq (I just entered the two lines of commands in README). After a few seconds, there raised an error:

‘’‘
return logging_output
UnboundLocalError: local variable 'logging_output' referenced before assignment
’‘’

Could anyone tell me what happened plz?

**Comment by neopro12** [comment]
Could you provide the complete error log and fairseq version?

**Comment by TIMAX-159** [comment]
fairseq version: 0.10.2

---------------------------------

2021-07-07 15:13:22 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 16.0
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/lightseq/bin/lightseq-train", line 8, in <module>
    sys.exit(ls_cli_main())
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/examples/training/fairseq/lightseq_fairseq_train_cli.py", line 10, in ls_cli_main
    cli_main(*args, **kwargs)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 283, in call_main
    torch.multiprocessing.spawn(
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/fairseq_cli/train.py", line 125, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/fairseq_cli/train.py", line 208, in train
    log_output = trainer.train_step(samples)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/site-packages/fairseq/trainer.py", line 705, in train_step
    return logging_output
UnboundLocalError: local variable 'logging_output' referenced before assignment

/home/liuyu/anaconda3/envs/lightseq/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by Taka152** [comment]
@TIMAX-159 Could you try only one worker? it seems failed on multi-gpu, haven't seen this before

**Comment by LYZJU2019** [comment]
It seems OK after I change the return value of `train_step` into `logging_outputs` (which is originally `logging_output`)
